"""One-shot Ch1 reframing edit for docs/Thesis.md.

Reads the file as bytes, locates the region from the start of the
"To address this gap" paragraph (line 139 region) through the end of the
chapter-roadmap paragraph ("Chapter 8 concludes the\nthesis."), and
replaces that region with the new Movements 3, 4, and 5.

Preserves CRLF line endings and existing non-breaking spaces in the
surrounding text by anchoring on clean byte sequences and writing the
replacement with CRLF endings.

Run once; idempotent only in the sense that re-running on the rewritten
file will fail to locate the old anchor.
"""
from __future__ import annotations

from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
THESIS = REPO / "docs" / "Thesis.md"

# Anchors are chosen to avoid non-breaking-space regions in the source.
START_ANCHOR = b"To address this gap, the present thesis is conducted in direct"
END_ANCHOR = b"concludes the\r\nthesis."

# CRLF line endings throughout to match the rest of the file.
NEW_BLOCK = (
    "To address this dual challenge, the present thesis develops a "
    "transferable\r\n"
    "multi-setup framework for context-aware multimodal anomaly "
    "detection and\r\n"
    "source localization in reversible Francis-type pump-turbines and "
    "similar\r\n"
    "hydraulic machinery, rather than a single-site diagnostic system. "
    "The\r\n"
    "framework is channel-agnostic and setup-agnostic by construction: "
    "a\r\n"
    "Set-Transformer pool over per-sensor "
    "tokens [@lee_set_2019; @zaheer_deep_2017]\r\n"
    "ingests an arbitrary number of microphones and accelerometers in "
    "arbitrary\r\n"
    "geometric arrangements; a YAML-driven dataset registry treats new "
    "sensor\r\n"
    "configurations as a configuration edit rather than a code change; "
    "per-dataset\r\n"
    "spectral hop and accelerometer sampling rates are propagated "
    "through the\r\n"
    "pipeline by metadata rather than by recompilation; and the "
    "unsupervised\r\n"
    "mode head is agnostic to the number of operating regimes K.\r\n"
    "\r\n"
    "The empirical validation rests on five controlled laboratory "
    "campaigns\r\n"
    "(D1–D5) on a custom three-dimensionally printed Francis "
    "pump-turbine\r\n"
    "scale prototype that the candidate designed and built. The five "
    "campaigns\r\n"
    "deliberately vary sensor count, sensor geometry, anomaly "
    "mechanism, and\r\n"
    "operating-condition controls so that the channel-agnostic "
    "architectural\r\n"
    "commitments are exercised against real heterogeneity rather than "
    "against\r\n"
    "simulated permutations. This methodological choice is grounded in "
    "an\r\n"
    "established tradition of scaled-model studies of Francis "
    "machinery\r\n"
    "[@experimental_vibrational_francis_2025; @francis_model_part_load_2025;"
    " @besni_machine_2025; @mixed_flow_pump_cavitation_2022],\r\n"
    "but extends that tradition in one specific direction the model-rig"
    " literature\r\n"
    "has not pursued: a multimodal-sensing test bench whose recordings,"
    " sensor\r\n"
    "topologies, and anomaly-position ground truth are documented to a "
    "standard\r\n"
    "suitable for machine-learning methodology validation across "
    "configurations.\r\n"
    "Such a substrate is unavailable in any single-site industrial "
    "dataset.\r\n"
    "\r\n"
    "The Rodundwerk II (ROW II) pumped-storage facility operated by "
    "illwerke vkw\r\n"
    "AG in Vorarlberg, Austria [@illwerke_vkw_rodundwerk_2026] is the "
    "named\r\n"
    "industrial target deployment for the framework, not its empirical "
    "basis.\r\n"
    "Commissioned in 1976 and rehabilitated between 2009 and 2011, ROW "
    "II houses\r\n"
    "a single 295 MW reversible Francis "
    "pump-turbine [@hydro_review_content_directors_voith_2010]\r\n"
    "operating across four modes (Standstill, Turbine, Pump, "
    "Phase-shifting).\r\n"
    "Phase-shifting requires actual grid coupling and reactive-power "
    "exchange\r\n"
    "and is therefore unreproducible on the bench-top prototype; the "
    "empirical\r\n"
    "evaluation in Chapters 5–6 consequently uses K = 3 modes "
    "({Pump, Standstill,\r\n"
    "Turbine}). The K-agnostic mode head and the channel-agnostic "
    "encoder pool\r\n"
    "make the K = 4 ROW II setting and its 13-sensor target array (nine"
    " airborne\r\n"
    "microphones plus four accelerometers across two elevations) a "
    "deployment-time\r\n"
    "configuration change. A registry stub for the ROW II array is "
    "shipped with\r\n"
    "the codebase, and a parallel mutual-information analysis of the "
    "existing\r\n"
    "illwerke vkw `Allg_M1` supervisory channel is included in "
    "Chapter 6 as\r\n"
    "concrete deployment-readiness evidence.\r\n"
    "\r\n"
    "The central research question addressed in this thesis is:\r\n"
    "\r\n"
    "> To what extent can latent representations of operational context"
    " be\r\n"
    "> extracted from synchronized multi-modal sensor streams (acoustic"
    " and\r\n"
    "> vibration), and does conditioning anomaly detection and source\r\n"
    "> localization on these representations improve performance under "
    "the\r\n"
    "> dual domain shifts induced by mode transitions within a setup "
    "and by\r\n"
    "> setup changes across machines?\r\n"
    "\r\n"
    "This central question decomposes into three sub-questions, each "
    "evaluated\r\n"
    "across the five lab campaigns rather than within a single setup:\r\n"
    "\r\n"
    "-   Which multimodal fusion strategy best learns operational-context"
    "\r\n"
    "    representations from acoustic and vibration streams across\r\n"
    "    heterogeneous sensor topologies and machine scales?\r\n"
    "\r\n"
    "-   Does conditioning anomaly detection on the inferred operational"
    "\r\n"
    "    context reduce false-positive rates under mode transitions, "
    "and does\r\n"
    "    the conditioning generalize across lab campaigns with different"
    "\r\n"
    "    sensor counts, sample rates, and anomaly geometries?\r\n"
    "\r\n"
    "-   How effectively can a learned source-localization model exploit"
    " the\r\n"
    "    fused representation and TDOA features to spatially attribute "
    "detected\r\n"
    "    anomalies, and what is the marginal contribution of "
    "structure-borne\r\n"
    "    accelerometer TDOAs over an acoustic-only baseline across "
    "multiple\r\n"
    "    anomaly-source configurations?\r\n"
    "\r\n"
    "The main contributions of this study are as follows. First, we "
    "design and\r\n"
    "implement a synchronized multimodal preprocessing pipeline whose "
    "data\r\n"
    "contract (`DataSegment`, `FeatureFrame`) and YAML-driven dataset "
    "registry\r\n"
    "make the integration of a new setup a configuration edit; the "
    "incremental\r\n"
    "integration of campaigns D1 through D5 is the empirical proof of "
    "this\r\n"
    "contract. Second, we investigate and validate a channel-agnostic\r\n"
    "cross-attention fusion architecture that combines a transformer\r\n"
    "cross-attention block with a Set-Transformer-style channel "
    "pool [@lee_set_2019],\r\n"
    "and we demonstrate that the same trained encoder ingests campaigns"
    " with\r\n"
    "three distinct sensor topologies (4 + 4, 5 + 5, 9 + 4) in a single"
    " training\r\n"
    "run without retraining. Third, we develop and evaluate a "
    "context-conditioned\r\n"
    "anomaly detection head and a FiLM-modulated source-localization "
    "head, both\r\n"
    "driven by a label-free latent context vector inferred by the "
    "fusion encoder;\r\n"
    "we report headline detection FPR-on-transition and localization "
    "mean-absolute-\r\n"
    "error numbers across all five prototype campaigns, including an "
    "ablation that\r\n"
    "quantifies the marginal contribution of structure-borne "
    "accelerometer TDOAs.\r\n"
    "Fourth — and as the meta-contribution that the prototype-first "
    "methodology\r\n"
    "makes explicit — the combination of the setup-agnostic data "
    "contract, the\r\n"
    "channel-agnostic encoder, the context-conditioned detection and "
    "localization\r\n"
    "heads, and a deployment-ready ROW II registry stub constitutes a "
    "transferable\r\n"
    "framework that bridges the lab-to-field gap by architectural "
    "design [@lab_to_field_2025]\r\n"
    "rather than by post-hoc transfer-learning fine-tuning.\r\n"
    "\r\n"
    "We structure this thesis as follows. Chapter 2 surveys related "
    "work in\r\n"
    "predictive maintenance, acoustic and vibration sensing, multimodal"
    " deep\r\n"
    "learning, anomaly detection, and source localization, and "
    "identifies the\r\n"
    "four gaps the proposed framework closes. Chapter 3 describes the "
    "3D-printed\r\n"
    "Francis pump-turbine prototype, the five lab campaigns and their "
    "varying\r\n"
    "sensor topologies, and the ROW II deployment-readiness section "
    "including\r\n"
    "the illwerke vkw `Allg_M1` supervisory-channel analysis. "
    "Chapter 4 presents\r\n"
    "the proposed multimodal architecture, covering the per-modality "
    "feature\r\n"
    "extraction branches, the cross-attention fusion mechanism, the "
    "Set-Transformer\r\n"
    "channel pool, the conditional anomaly detection head, and the "
    "FiLM-modulated\r\n"
    "source-localization head. Chapter 5 details the experimental "
    "setup, including\r\n"
    "preprocessing, training protocols, baseline configurations, and "
    "evaluation\r\n"
    "metrics. Chapter 6 presents the experimental results, which are "
    "discussed in\r\n"
    "Chapter 7 alongside limitations and directions for future work. "
    "Chapter 8\r\n"
    "concludes the thesis."
)


def main() -> None:
    data = THESIS.read_bytes()
    start = data.find(START_ANCHOR)
    if start == -1:
        raise SystemExit("Start anchor not found; aborting.")
    # Find END_ANCHOR strictly after START_ANCHOR; the search is bounded
    # so that an accidental match in a later chapter cannot eat the file.
    end = data.find(END_ANCHOR, start)
    if end == -1:
        raise SystemExit("End anchor not found; aborting.")
    end_inclusive = end + len(END_ANCHOR)

    new_bytes = NEW_BLOCK.encode("utf-8")
    rewritten = data[:start] + new_bytes + data[end_inclusive:]
    THESIS.write_bytes(rewritten)
    removed = end_inclusive - start
    added = len(new_bytes)
    print(f"Replaced {removed} bytes with {added} bytes "
          f"(delta {added - removed:+d} bytes).")


if __name__ == "__main__":
    main()
